### ISSUE TITLE
Source? License?

### ISSUE THREAD

**Issue by mathiasbynens** [jnovack/pokemon-svg#1]
The commit message of https://github.com/jnovack/pokemon-svg/commit/9570433eeaa1e588dc2fa1fb4329279aba1a9b54 mentions “import” which begs the question where these SVGs have been imported from. Could this be mentioned in the README?

Could you add a license?

**Comment by jnovack** [comment]
Fixed in 866954ea321e240aa0fa5d70981d5c4709dffdd9

Files are Copyright Nintendo/Game Freak/The PokeMon Company and are here under fair use in a non-commercial project.

**Comment by mathiasbynens** [comment]
Thanks for clarifying! Still wondering where you got the SVGs though :P

**Comment by jnovack** [comment]
I have higher than average IV stats in "google-fu" ;)

**Comment by mathiasbynens** [comment]
Is this the source? http://veekun.com/dex/media/pokemon/dream-world/

**Comment by jnovack** [comment]
You win!
