### ISSUE TITLE
Add leading zeros to the filenames

### ISSUE THREAD

**Issue by lipis** [jnovack/pokemon-svg#2]
- `1.svg` >> `001.svg`
- `25.svg` >> `025.svg`
- etc

**Comment by jnovack** [comment]
Pokemon Go does not use leading-zeros for it's Pokemon numbers in the return data.  It aggravates me as well (my OCD wants leading zeros), however, they made the standard.

It's more natural to write `PokeNumber.svg` versus `function(PokeNumber).svg` in every line of code that needs it.
